### ISSUE TITLE
Feature request: unhide gauges

### ISSUE THREAD

**Issue by ZHANGTIANYAO1** [Project-Hatchet/public_h-60#308]
## **Describe feature request.**

Is there any way I can unhide the advanced flight gauges？

**Comment by AdozenBABYdogs** [comment]
Check your Arma 3 Game Options menu to see if they are hidden.  If they aren't I am unsure, but a temporary fix would be using the PFD page (by default on the right hand MFD when you get in the pilot seat)  All of the insturments on the PFD are accurate and calculated just like the AFM insturment panel, but specficic to feet instead of meters

**Comment by ZHANGTIANYAO1** [comment]
Thanks for your reply, I'm sure I turned them on in the game options. The PFD was great but it couldn't move with my perspective, which made it difficult for a player without a Collective Pitch Control or throttle to move the perspective and pay attention to their pitch angle.

**Comment by ZHANGTIANYAO1** [comment]
@AdozenBABYdogs

**Comment by PhantomDevTeam** [comment]
We hide them through a script, you won't be able to turn them on.
The HMD provides you with pitch, speed, elevation, ascend/descend rate, etc. The PFD combined with the EICAS provides all the information you need as well.

**Comment by ZHANGTIANYAO1** [comment]
Can I ask which script does this function? @PhantomDevTeam

**Comment by BroBeansCPG** [comment]
It’s set in the config so you can’t change it without repacking our mod. Which means you’ll be unable to distribute it as per our license. And if it’s not contributing to the development of our project we’d probably kindly ask you not to pack your own versions of our mod even for private use. 

It’ll be in the rscTitles though if you want to look for it.

**Comment by ZHANGTIANYAO1** [comment]
Thank you very much. I will not be repackaging this mod. But I would really love to have a toggle hide feature. I know it's not realistic, but as I said before, a lot of players don't have enough equipment to experience a more realistic model flight. It would help us a lot if you could add this feature. Thank you again for your help. @BroBeansCPG

**Comment by PhantomDevTeam** [comment]
It takes some getting used to but there is no extra equipment needed. Everything can be done with free-look (default keybind is Alt). During the day you're flying by feel most of the time and you don't need to use the instruments and night the HMD provides all the necessary information. After you fly it for a bit it becomes second nature.

BroBeans will have to correct me but I don't think we currently have plans of enabling the vanilla GUI, sorry. 

*Edit grammar

**Comment by BroBeansCPG** [comment]
Pretty much yeah, it won’t be happening because the idea of all these systems is to show that information in an alternative form.

We don’t want all these work done on instruments to be wasted by people just using vanilla UI 😆 

I understand your concerns and all I can recommend is familiarising yourself with the HMD features and the PFD/EICAS pages. 

All the critical information can be displayed on the HMD.

What gauge in particular do you require most? Collective input amount? Pitch and Roll? VSI? These are all displayed on the HMD (Helmet Mounted Display)


You can turn on the HMD permanently in your addon settings or through the FMS (Kneepad screen)
FMS>MSN SYS>HMD>ON (with your choice of imperial/metric) 

The HMD actually displays more information than the vanilla UI and is less intrusive on your display. 
In the full display mode it shows 

Altitude
Speed
Pitch & Roll
Slip
Collective Input (%) (C value bottom left)
Torque (%) (Q value bottom left)
Vertical Speed Indicator 
Heading
Current Waypoint
3D waypoint indicator
ILS

![HMD Image](https://user-images.githubusercontent.com/14846032/153855737-03180f7a-155c-4d4d-bd51-74752ac1ec49.png)
