### ISSUE TITLE
Bug: Laser designator default code does not match FLIR channels 

### ISSUE THREAD

**Issue by Havoc-1** [Project-Hatchet/public_h-60#426]
# Bug Report

## **Description:**
Currently very inconvinent to self-lase. Preset channels from Hatch (CHAN A-F) still use the old default laser codes [1111 - 1114], since ACE 3.16.0 the new default laser code is now 1688.

In order to be able to self lase, must go into FLIR system and adjust laser code via ACE keybinds to the laser codes listed in CHAN A-F

### **Expected Behavior**
Hellfire-K should automatically track laser from helicopter. 

### Steps to Reproduce the Issue

1. Follow typical startup procedure 
2. Boot up FLIR system 
3. Fire laser
4. Fire HELLFIRE-K 

### **Screenshots**
![HatchDefaultLaserFLIR](https://github.com/Project-Hatchet/H-60/assets/87105826/64c76b59-23a0-4cb9-b5a4-6149ebe55905)
![HatchDefaultChannel](https://github.com/Project-Hatchet/H-60/assets/87105826/05bb2b20-f3aa-4816-936f-ea7e0972ca08)

### **Additional context**

Link to ACE pull request showing the change to laser codes. 
 https://github.com/acemod/ACE3/pull/9434

**Comment by BroBeansCPG** [comment]
Thanks, 

Fixed for next update, no eta. 

**Alternative Temp Fix:**

If you cycle the LSR channel back to Alpha when you set up the flir it works fine, alternatively, for less clicks, cycle to Bravo and change the missile code to bravo also. 

There's no requirement to use the keybinds in ace. 

alternatively as a mission maker, run this on the helis `_this setVariable ["ace_laser_code", 1111];`

we never had to set the code initially because it was default, so thanks ace, completely unnecessary change 🤣

guide on laser codes here: 
https://uh-60m.gitbook.io/workspace/guides/multi-functional-displays/forward-looking-infrared-camera#_imamzrq1fp8

**Comment by Riverman02** [comment]
ACE Update reverted default laser code to 1111
